site_name: SQANTI3 Documentation
site_url: https://github.com/ConesaLab/SQANTI3/

theme:
  name: material
  palette:
    # Palette toggle for Light Mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for Dark Mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
  
  icon:
    logo: material/library
  
  font:
    text: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif
    code: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Introduction to SQANTI3: Introduction-to-SQANTI3.md
  - Dependencies and installation: Dependencies-and-installation.md
  - Version history: Version-history.md
  - Isoform classification - categories and subcategories: SQANTI3-isoform-classification:-categories-and-subcategories.md
  - Running SQANTI3 from the wrapper: Running-SQANTI3-from-the-wrapper.md
  - Running SQANTI3 Quality Control: Running-SQANTI3-Quality-Control.md
  - Understanding the output of SQANTI3 QC: Understanding-the-output-of-SQANTI3-QC.md
  - IsoAnnotLite: IsoAnnotLite.md
  - Running SQANTI3 filter: Running-SQANTI3-filter.md
  - Running SQANTI3 rescue: Running-SQANTI3-rescue.md
  - Tutorial - running SQANTI3 on an example dataset: Tutorial:-running-SQANTI3-on-an-example-dataset.md
  - Running SQANTI-reads: Running-SQANTI‚Äêreads.md
  - Memory requirements and parallelization: SQANTI3-memory-requeriments-and-paralellization.md