site_name: SQANTI3 Documentation
site_url: https://github.com/ConesaLab/SQANTI3/

theme:
  name: material
  palette:
    # Palette toggle for Light Mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for Dark Mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections  # Groups sidebar links into sections
    - navigation.expand    # Auto-expand sidebar
    - navigation.top       # "Back to top" button
    - content.code.copy    # Adds a copy button to all code blocks
  
  logo: assets/2025-4_Logos_AnaConesa_V3_SQANTI-lupa.png
  favicon: assets/2025-4_Logos_AnaConesa_V3_SQANTI-lupa.png
  
  font:
    text: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif
    code: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace

# extra_css:
#   - stylesheets/extra.css

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Introduction to SQANTI3: Introduction-to-SQANTI3.md
  - Dependencies and installation: Dependencies-and-installation.md
  - Version history: Version-history.md
  - Isoform classification - categories and subcategories: SQANTI3_isoform_classification.md
  - Running SQANTI3 from the wrapper: Running-SQANTI3-from-the-wrapper.md
  - Running SQANTI3 Quality Control: Running-SQANTI3-Quality-Control.md
  - Understanding the output of SQANTI3 QC: Understanding-the-output-of-SQANTI3-QC.md
  - IsoAnnotLite: IsoAnnotLite.md
  - Running SQANTI3 filter: Running-SQANTI3-filter.md
  - Running SQANTI3 rescue: Running-SQANTI3-rescue.md
  - Tutorial - running SQANTI3 on an example dataset: Tutorial:-running-SQANTI3-on-an-example-dataset.md
  - Running SQANTI-reads: Running-SQANTI‚Äêreads.md
  - Memory requirements and parallelization: SQANTI3-memory-requeriments-and-paralellization.md